
/*
===============================================================================
                       categorical_analysis_exploration
===============================================================================

Purpose:
    - Analyze metrics grouped by categorical dimensions such as 
      country, gender, category, and customer.
    - Understand customer distribution, product distribution, 
      and revenue contribution across categories.
    - Identify top-performing categories, customers, and regions.

Key Metrics Calculated:
    - Total customers by country
    - Total customers by gender
    - Total products by category
    - Average product cost per category
    - Total revenue generated per category
    - Total revenue generated per customer
    - Distribution of sold items across countries

SQL Functions Used:
    - COUNT()     -- count customers
    - SUM()       -- total revenue, total items, total products
    - AVG()       -- average cost
    - GROUP BY    -- group metrics by categorical fields
    - ORDER BY    -- sort results for insights

===============================================================================
*/



/* =============================================================================
   Find total customers by countries
   ========================================================================== */
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;



/* =============================================================================
   Find total customers by gender
   ========================================================================== */
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;



/* =============================================================================
   Find total products by category
   ========================================================================== */
SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;



/* =============================================================================
   Find the average cost in each category
   ========================================================================== */
SELECT
    category,
    AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;



/* =============================================================================
   Find the total revenue generated for each category
   ========================================================================== */
SELECT 
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
    ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;



/* =============================================================================
   Find total revenue generated by each customer
   ========================================================================== */
SELECT 
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
    ON f.customer_key = c.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;



/* =============================================================================
   Find the distribution of sold items across countries
   ========================================================================== */
SELECT 
    c.country,
    SUM(f.quantity) AS total_items_sold
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
    ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_items_sold DESC;
